### ISSUE TITLE
Error while executing command: unexpected book metadata list count: 0, expected 1

### ISSUE THREAD

**Issue by MrHid3** [tp86/legimi-go#7]
Error occurs while downloading any book, after it tries to download it 5 times
![immagine](https://github.com/user-attachments/assets/b8441362-798e-46c8-b48c-f243f38b6e3b)

**Comment by 73rrto4r** [comment]
I had similar issue the other day.

Wait for an hour or two and try again.
This can happen when using official Legimi app as well.

**Comment by MrHid3** [comment]
It works now, thanks. Kinda need to hijack this thread to ask you a question. Are you fine with me using your reverse-engineered webcode in a GUI app?

**Comment by 73rrto4r** [comment]
Great that it worked! You need to ask tp86 as it is his code.  I'm just a user. I'd be interested to see your GUI so keep me posted if you get permission and it works.

**Comment by MrHid3** [comment]
Bruh, I didn't notice it wasn't him replying. Hope he sees this soon and replies @tp86

**Comment by tp86** [comment]
Sorry for late response, I have new family member born recently ;)

It's great to see you guys helping each other. Thanks @73rrto4r for replying. You are right, in such cases, one just needs to wait and try to download later. I guess Legimi server has to create individual link for download to make it work only with your Kindle and sometimes it's lagging.

Anyway, official Legimi app should always be a reference.

@MrHid3 I guess you can make some GUI app. I was planning to do it as well, but I didn't have enough time for this yet. Are you going to create a fork and frontend for my app, or make something new based on the protocol? Just curious, either way is fine.

**Comment by MrHid3** [comment]
Probably gonna rewrite it in C++ since I'll be using Qt (also it's a school project so half of it shouldn't be someone else's). Will give you full credit for your work ofc

**Comment by 73rrto4r** [comment]
@tp86 Congratulations!!!

**Comment by tp86** [comment]
Good luck with your project! If you need any help with understanding what's going on, I'll try to help. I'm not at all Legimi protocol expert, though.

**Comment by MrHid3** [comment]
Sure, thanks!

**Comment by tp86** [comment]
> @tp86 Congratulations!!!

Thanks!
:tada:
